- name: Say Hello Playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Print a greeting
      ansible.builtin.debug:
        msg: "The user said: {{ user_greeting | default('Hello, World!') }}"
